In [1]:
import pandas as pd

In [10]:
df = pd.read_excel(
    r"C:\Users\Bala murukan\Downloads\New folder\EV_Intelligencee_platform\01_Raw_Data\CMO-Historical-Data-Monthly.xlsx",
    sheet_name="Monthly Prices",
    header=None,
    engine="openpyxl"
)

In [11]:
df.head(10)

,0,1,2,3,4,5,6,7,8,9,...,62,63,64,65,66,67,68,69,70,71
0,World Bank Commodity Price Data (The Pink Sheet),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"monthly prices in nominal US dollars, 1960 to ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(monthly series are available only in nominal ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Updated on August 04, 2026",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,"Crude oil, average","Crude oil, Brent","Crude oil, Dubai","Crude oil, WTI","Coal, Australian","Coal, South African **","Natural gas, US","Natural gas, Europe","Liquefied natural gas, Japan",...,Aluminum,"Iron ore, cfr spot",Copper,Lead,Tin,Nickel,Zinc,Gold,Platinum,Silver
5,NaN,($/bbl),($/bbl),($/bbl),($/bbl),($/mt),($/mt),($/mmbtu),($/mmbtu),($/mmbtu),...,($/mt),($/dmtu),($/mt),($/mt),($/mt),($/mt),($/mt),($/troy oz),($/troy oz),($/troy oz)
6,1960M01,1.6,1.6,1.6,…,…,…,0.14,0.4,…,...,511,11.4,715,206,2180,1631,261,35,84,0.9
7,1960M02,1.6,1.6,1.6,…,…,…,0.14,0.4,…,...,511,11.4,728,204,2180,1631,245,35,84,0.9
8,1960M03,1.6,1.6,1.6,…,…,…,0.14,0.4,…,...,511,11.4,685,210,2174,1631,249,35,84,0.9
9,1960M04,1.6,1.6,1.6,…,…,…,0.14,0.4,…,...,511,11.4,723,214,2178,1631,255,35,84,0.9

In [12]:
print(df.iloc[4:10, 0:3])

         0                   1                 2
4      NaN  Crude oil, average  Crude oil, Brent
5      NaN             ($/bbl)           ($/bbl)
6  1960M01                 1.6               1.6
7  1960M02                 1.6               1.6
8  1960M03                 1.6               1.6
9  1960M04                 1.6               1.6

In [13]:
# Skip the header rows (usually first 6 rows)
df = df.iloc[6:].copy()

# Keep only first two columns (Date and Crude oil average)
df = df.iloc[:, [0, 1]]

df.columns = ["Date", "Crude_Oil_Price"]

df.head(10)

       Date Crude_Oil_Price
6   1960M01             1.6
7   1960M02             1.6
8   1960M03             1.6
9   1960M04             1.6
10  1960M05             1.6
11  1960M06             1.6
12  1960M07             1.6
13  1960M08             1.6
14  1960M09             1.6
15  1960M10             1.6

In [14]:
df["Date"] = df["Date"].astype(str)
df = df[df["Date"].str.contains("M", na=False)]   # Keep only monthly rows

df["Year"] = df["Date"].str[:4].astype(int)
df["Crude_Oil_Price"] = pd.to_numeric(df["Crude_Oil_Price"], errors="coerce")

df = df.dropna(subset=["Crude_Oil_Price"])
df.head()

       Date  Crude_Oil_Price  Year
6   1960M01              1.6  1960
7   1960M02              1.6  1960
8   1960M03              1.6  1960
9   1960M04              1.6  1960
10  1960M05              1.6  1960

In [15]:
annual = df.groupby("Year")["Crude_Oil_Price"].mean().reset_index()
annual = annual[(annual["Year"] >= 2015) & (annual["Year"] <= 2024)]

print(annual)
print("Final rows:", len(annual))

    Year  Crude_Oil_Price
55  2015        50.750000
56  2016        42.808333
57  2017        52.816667
58  2018        68.358333
59  2019        61.416667
60  2020        41.250000
61  2021        69.083333
62  2022        97.100000
63  2023        80.766667
64  2024        78.725000
Final rows: 10

In [16]:
annual.to_csv(
    r"C:\Users\Bala murukan\Downloads\New folder\EV_Intelligencee_platform\02_Cleaned_Data\cleaned_crude_oil.csv",
    index=False
)

print("Crude Oil dataset cleaned successfully!")
print("Final rows:", len(annual))

Crude Oil dataset cleaned successfully!
Final rows: 10